In [2]:
# import library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv(r"D:\telegram\6th - mlr\6th - mlr\MLR\House_data.csv")

In [4]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [5]:
x = df.drop(["price","id","date"],axis=1)
y = df.iloc[:,2]

In [6]:
x.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [7]:
y.head()

0    221900.0
1    538000.0
2    180000.0
3    604000.0
4    510000.0
Name: price, dtype: float64

In [8]:
# import scikit learn libarary
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [9]:
x_train.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
5268,3,1.0,1570,5510,1.0,0,0,4,7,1070,500,1940,0,98115,47.6942,-122.319,1770,6380
16909,3,2.5,1780,11000,1.0,0,0,4,8,1210,570,1980,0,98006,47.5574,-122.149,2310,9700
16123,3,1.5,1090,9862,1.0,0,0,3,8,1090,0,1987,0,98074,47.6256,-122.036,1710,9862
12181,4,2.5,2210,7079,2.0,0,0,3,8,2210,0,1993,0,98031,47.4206,-122.183,1970,7000
12617,3,2.5,1800,4763,2.0,0,0,3,7,1240,560,1985,0,98119,47.6460,-122.362,1790,4763

In [10]:
y_test.tail()

5427     844000.0
16547    335500.0
4585     369950.0
17762    300000.0
16323    575950.0
Name: price, dtype: float64

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [12]:
y_pred =regressor.predict(x_test)

In [13]:
y_pred

array([ 378448.21562235, 1539749.3694526 ,  544459.90274488, ...,
        359857.21092687,  207005.8334062 ,  433639.78567724],
      shape=(4323,))

In [14]:
m =regressor.coef_
print(m)

[-3.46742834e+04  3.94309995e+04  1.12610340e+02  1.75888746e-01
  7.42456797e+03  6.05600540e+05  5.27368869e+04  2.61695179e+04
  9.35901530e+04  7.27875916e+01  3.98227483e+01 -2.60713695e+03
  2.01053037e+01 -5.67468820e+02  6.04865960e+05 -2.22392027e+05
  2.42333810e+01 -4.67450069e-01]

In [15]:
c = regressor.intercept_
print(c)

4166134.7323094746

In [16]:
df.shape

(21613, 21)

In [17]:
x = np.append(
    arr=np.ones((21613, 1)).astype(int),
    values=x,
    axis=1
)

In [18]:
x

array([[ 1.00000e+00,  3.00000e+00,  1.00000e+00, ..., -1.22257e+02,
         1.34000e+03,  5.65000e+03],
       [ 1.00000e+00,  3.00000e+00,  2.25000e+00, ..., -1.22319e+02,
         1.69000e+03,  7.63900e+03],
       [ 1.00000e+00,  2.00000e+00,  1.00000e+00, ..., -1.22233e+02,
         2.72000e+03,  8.06200e+03],
       ...,
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  2.00700e+03],
       [ 1.00000e+00,  3.00000e+00,  2.50000e+00, ..., -1.22069e+02,
         1.41000e+03,  1.28700e+03],
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  1.35700e+03]], shape=(21613, 19))

In [19]:
import statsmodels.api as sm
x_opt=x[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.699
Model:                            OLS   Adj. R-squared:                  0.699
Method:                 Least Squares   F-statistic:                     3140.
Date:                Tue, 07 Jul 2026   Prob (F-statistic):               0.00
Time:                        15:59:11   Log-Likelihood:            -2.9462e+05
No. Observations:               21613   AIC:                         5.893e+05
Df Residuals:                   21596   BIC:                         5.894e+05
Df Model:                          16
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6.092e+06   2.93e+06      2.079      0.038    3.47e+05    1.18e+07
x1         -3.532e+04   1891.036    -18.676      0.000    -3.9e+04   -3.16e+04
x2           4.16e+04   3254.494     12.782      0.000    3.52e+04     4.8e+04
x3           109.8770      2.268     48.438      0.000     105.431     114.323
x4            -0.0438      0.035     -1.259      0.208      -0.112       0.024
x5          7347.7971   3595.835      2.043      0.041     299.695    1.44e+04
x6          5.819e+05   1.74e+04     33.502      0.000    5.48e+05    6.16e+05
x7          5.282e+04   2141.336     24.668      0.000    4.86e+04     5.7e+04
x8          2.617e+04   2352.539     11.126      0.000    2.16e+04    3.08e+04
x9          9.619e+04   2153.336     44.670      0.000     9.2e+04       1e+05
x10           70.3130      2.253     31.209      0.000      65.897      74.729
x11           39.5650      2.648     14.941      0.000      34.375      44.755
x12        -2625.8424     72.695    -36.121      0.000   -2768.331   -2483.354
x13           19.5418      3.657      5.343      0.000      12.373      26.711
x14         -583.8375     33.005    -17.689      0.000    -648.529    -519.146
x15          6.04e+05   1.07e+04     56.251      0.000    5.83e+05    6.25e+05
x16        -2.203e+05   1.31e+04    -16.821      0.000   -2.46e+05   -1.95e+05
x17           20.7848      3.446      6.032      0.000      14.031      27.538
==============================================================================
Omnibus:                    18388.489   Durbin-Watson:                   1.990
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1871584.420
Skew:                           3.567   Prob(JB):                         0.00
Kurtosis:                      48.027   Cond. No.                     4.10e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.27e-21. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [20]:
x_opt= x[:,[0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17]]
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.699
Model:                            OLS   Adj. R-squared:                  0.699
Method:                 Least Squares   F-statistic:                     3349.
Date:                Tue, 07 Jul 2026   Prob (F-statistic):               0.00
Time:                        15:59:11   Log-Likelihood:            -2.9462e+05
No. Observations:               21613   AIC:                         5.893e+05
Df Residuals:                   21597   BIC:                         5.894e+05
Df Model:                          15
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.733e+06   2.92e+06      1.965      0.049     1.5e+04    1.15e+07
x1         -3.513e+04   1885.032    -18.635      0.000   -3.88e+04   -3.14e+04
x2          4.165e+04   3254.270     12.799      0.000    3.53e+04     4.8e+04
x3           109.5636      2.255     48.593      0.000     105.144     113.983
x4          7635.9919   3588.584      2.128      0.033     602.102    1.47e+04
x5          5.822e+05   1.74e+04     33.520      0.000    5.48e+05    6.16e+05
x6          5.269e+04   2138.589     24.636      0.000    4.85e+04    5.69e+04
x7           2.62e+04   2352.463     11.138      0.000    2.16e+04    3.08e+04
x8          9.618e+04   2153.358     44.666      0.000     9.2e+04       1e+05
x9            69.9939      2.239     31.265      0.000      65.606      74.382
x10           39.5698      2.648     14.943      0.000      34.379      44.760
x11        -2621.6163     72.619    -36.101      0.000   -2763.954   -2479.278
x12           19.5673      3.657      5.350      0.000      12.398      26.736
x13         -584.2421     33.004    -17.702      0.000    -648.932    -519.553
x14          6.05e+05   1.07e+04     56.470      0.000    5.84e+05    6.26e+05
x15        -2.231e+05   1.29e+04    -17.293      0.000   -2.48e+05   -1.98e+05
x16           20.9717      3.442      6.092      0.000      14.224      27.719
==============================================================================
Omnibus:                    18405.179   Durbin-Watson:                   1.990
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1880349.801
Skew:                           3.571   Prob(JB):                         0.00
Kurtosis:                      48.133   Cond. No.                     3.98e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.31e-21. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [21]:
# bais and varince
bais =regressor.score(x_train,y_train)
bais

0.7005349311144583

In [22]:
varince= regressor.score(x_test,y_test)
varince

0.6949310095117853

In [23]:
regressor

LinearRegression()

In [24]:
import joblib # create pipeline
joblib.dump(regressor, "Desktop.pkl")

['Desktop.pkl']

In [25]:
pwd

'c:\\machine learning\\regression\\multiple-linear-regression-house-price'

In [26]:
model = joblib.load("Desktop.pkl") # pickle

In [27]:
pwd

'c:\\machine learning\\regression\\multiple-linear-regression-house-price'